language: php
sudo: false
cache:
  directories:
    - vendor
php:
 - 5.5
 - 5.6
 - 7.0
 - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
 - if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then phpenv config-add travis.php.ini; fi
 - cd htdocs
 - mysql -e 'create database symfony;'
 - sh -c 'sed -i "s/db.password=root/db.password=/" app/config/default.properties'
 - cp codeception.yml.dist codeception.yml
 - ant install
 - travis_retry composer selfupdate
 - travis_retry composer install --no-interaction
 - ant build
 - php bin/codecept build

script:
 - php bin/codecept run
