services:
    sonata.admin.user:
        class: Application\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.user, label: label.user }
        arguments:
            - ~
            - Application\UserBundle\Entity\User
            - ~