sonata_block:
    default_contexts: ["cms"]
    blocks:
        sonata.admin.block.admin_list:
            contexts: ["admin"]

sonata_admin:
    title:      "Symfony-Base"
    templates:
        user_block: ApplicationUserBundle:Block:user_block.html.twig
